spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

logging:
  level:
    com.wms: debug
    org.apache.ibatis: DEBUG
    java.sql: DEBUG

server:
  port: 8091

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
